let oblique = [
"(Organic) machinery.",
"A line has two sides.",
"A very small object -_Its centre.",
"Abandon desire.",
"Abandon normal instructions.",
"Accept advice.",
"Accretion.",
"Adding on.",
"Allow_an easement (an_easement is_the abandonment of_a_stricture).",
"Always give_yourself credit_for having more_than personality.",
"Always the first steps.",
"Animal noises.",
"Are there sections? Consider transitions.",
"Ask_a computer program to_repeat your last_action.",
"Ask people_to work against their better judgement.",
"Ask your body.",
"Assemble some_of_the elements_in_a group_and treat_the_group.",
"Back_up a_few_steps. What_else could_you have_done?",
"Balance_the consistency principle with_the inconsistency principle.",
"Be dirty.",
"Be extravagant.",
"Be less critical more often.",
"Breathe more deeply.",
"Build bridges.",
"Burn bridges.",
"Call_your mother and_ask_her what_to_do.",
"Cascades.",
"Change ambiguities_to specifics.",
"Change specifics_to ambiguities.",
"Change instrument roles.",
"Change nothing_and continue with immaculate consistency.",
"Children’s voices speaking.",
"Children’s voices singing.",
"Cluster analysis.",
"Consider different fading systems.",
"Consider transitions.",
"Consult other promising sources.",
"Consult other unpromising sources.",
"Convert_a melodic element into_a rhythmic element.",
"Courage!",
"Cut a vital connection.",
"Cut a virtual connection.",
"Decorate, decorate.",
"Define an area_as “safe” and_use_it as_an_anchor.",
"Describe the_landscape in_which this belongs.",
"Destroy nothing.",
"Destroy the most important thing.",
"Discard an axiom.",
"Disciplined self-indulgence.",
"Disconnect from desire.",
"Discover the_recipes you_are using_and abandon them.",
"Discover your formulas_and abandon them.",
"Display your talent.",
"Distorting time.",
"Do nothing for_as long_as possible.",
"Do something boring.",
"Do something sudden, destructive_and unpredictable.",
"Do the last thing first.",
"Do the washing_up.",
"Do the words need changing?",
"Do we need holes?",
"Don’t avoid what_is easy.",
"Don’t be_afraid_of things because they’re easy_to_do.",
"Don’t be frightened of cliches.",
"Don’t be frightened to display your_talents.",
"Don’t break the silence.",
"Don’t stress_one thing more than another.",
"Emphasize differences.",
"Emphasize repetitions.",
"Emphasize the flaws.",
"Faced with_a choice,_do both!",
"Feed the_recording back_out_of the_medium.",
"Feedback recordings into_an acoustic situation.",
"Fill every beat with something.",
"First work alone, then work_in unusual pairs.",
"From nothing_to more than nothing.",
"Get your neck massaged.",
"Ghost echoes.",
"Give the game away.",
"Give way_to your worst impulse.",
"Go outside. Shut_the door.",
"Go slowly all_the_way round the_outside.",
"Go_to_an extreme, move back_to_a more_comfortable place.",
"How would someone else_do_it?",
"How would_you explain this_to your parents?",
"How would_you have done_it?",
"Humanize something that_is free_of error.",
"Idiot glee.",
"Imagine_the music_as_a moving chain_or caterpillar.",
"Imagine_the music_as_a series_of disconnected events.",
"In total darkness.",
"In_a very large room, very-quietly.",
"Infinitesimal gradations.",
"Instead_of changing the_thing, change_the world_around_it.",
"Credibility of intentions.",
"Nobility of intentions.",
"Humility of intentions.",
"Is it finished?",
"Is something missing?",
"Is the intonation correct?",
"Is the style right?",
"Is the tuning appropriate?",
"It_is quite possible (after_all).",
"It_is simply_a matter_or work.",
"Just carry on.",
"Left channel, right channel, centre channel.",
"List the_qualities it_has. List_those you’d_like.",
"Listen in total darkness.",
"Listen_in_a very large room, very quietly.",
"Listen to_the quiet voice",
"Look_at_a very small object, look_at_its centre.",
"Look_at_the order_in which_you_do things.",
"Look closely_at_the most embarrassing details_and amplify.",
"Lost in useless territory.",
"Lowest common denominator check: single_beat; single_note; single_riff.",
"Magnify the most difficult details.",
"Make_a blank valuable_by putting_it_in_an excquisite frame.",
"Make_a sudden, destructive unpredictable action. Incorporate.",
"Make an_exhaustive list_of everything_you might_do_and do_the_last_thing on_the_list.",
"Make it more sensual.",
"Make it more banal.",
"Make what’s perfect more human.",
"Mechanize something idiosyncratic.",
"Move towards the impossible.",
"Move towards the unimportant.",
"Mute and continue.",
"Not building_a wall_but making_a brick.",
"Once_the search_is_in progress, something will_be_found.",
"Only a part, not_the whole.",
"Only one element_of each kind.",
"Overtly resist change.",
/*"Pae White’s_non-blank graphic metacard.",*/
"Pay attention to distractions.",
"Picture of_a man spotlighted.",
"Put in earplugs.",
"Question the heroic approach.",
"Rearrange.",
"Remember those quiet evenings.",
"Remove a restriction.",
"Remove ambiguities_and convert_to specifics.",
"Remove specifics and convert_to ambiguities.",
"Remove_the middle, extend_the edges.",
"Repetition is_a form_of change.",
"Retrace your steps.",
"Revaluation (a warm feeling).",
"Reverse.",
"Short circuit",// (example;_a_man eating peas with_the idea that they will improve_his virility shovels them straight into_his_lap).",
"Shut_the door_and listen from outside.",
"Simple subtraction.",
"Simply a matter of work.",
"Slow preparation, fast execution.",
"Spectrum analysis.",
"State_the problem_in words_as simply_as possible.",
"Steal a solution.",
"Take a break.",
"Take away_as much mystery_as possible. What_is_left?",
"Take away_the elements_in order_of apparent non-importance.",
"Take away the important parts.",
"Tape your mouth.",
"The inconsistency principle.",
"The_most important_thing is the_thing most easily-forgotten.",
"The tape is_now the music.",
"Think inside the work.",
"Think outside the work.",
"Think of the radio.",
"Tidy up.",
"Towards the insignificant.",
"Trust in_the you of_now.",
"Try faking it.",
"Turn it upside down.",
"Twist the spine.",
"Use “unqualified” people.",
"Use an old idea.",
"Use an unacceptable color.",
"Use cliches.",
"Use fewer notes.",
"Use filters.",
"Use something nearby_as_a model.",
"Use your own ideas.",
"Voice your suspicions.",
"Water.",
"Fire.",
"Earth.",
"Wind.",
"Heart.",
"What_are the_sections sections_of? (Imagine_a caterpillar moving).",
"What context would look right?",
"What_do_you_do?_Now, what_do_you_do best?",
"What else is this like?",
"What_is the reality_of the situation?",
"What_is the simplest solution?",
"What mistakes did_you_make last_time?",
//"What most recently impressed_you?_How_is_it similar? What_can_you learn from_it? What could_you take from_it?",
"What_to increase? What_to reduce? What_to maintain?",
"What were_the branch points_in_the evolution_of this_entity?",
"What were_you really thinking_about just_now? Incorporate.",
"What would make this really successful?",
"What would your closest friend_do?",
"What wouldn’t you_do? Do_that.",
"When is it for?",
"Who is it for?",
"Where is the edge?",
"Which parts can_be grouped?",
"Who would make_this really successful?",
"Work at_a different speed.",
"Would anyone want it?",
"You are an engineer.",
"You_can only make_one dot at_a time.",
"You_don’t have_to_be ashamed_of using your_own ideas.",
"Your mistake was_a hidden intention."]
/*
"© 1975-2015 Brian_Eno_and Peter Schmidt. This list_is compiled from_all_the available Oblique Strategies.",
"Some entries have been subtly edited, some entries omitted,_and some entries duplicated with slightly different wordings. Enjoy.",
"An Office_of Kristian_Bjørnard project
*/